ARG DOCKER_IMAGE_BASED

FROM ${DOCKER_IMAGE_BASED}

COPY ./deploy/nginx.conf /etc/nginx/nginx.conf
COPY ./deploy/php-fpm.conf /usr/local/etc/php-fpm.d/www.conf
COPY ./deploy/php.ini /usr/local/etc/php/php.ini
COPY ./deploy/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

WORKDIR /var/www/html

COPY --chown=www-data . .

RUN composer install \
    && php artisan storage:link \
    && php artisan cache:clear 

RUN rm -Rf deploy/ \
    && composer --version \
    && nginx -v \
    && php -m \
    && cat .env \
    && ls -lah \
    && ls -lah /etc/nginx/

EXPOSE 80
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisor/conf.d/supervisord.conf"]
